apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    cluster.name: kubernetes-logging

    node.name: ${NODE_NAME}
    node.master: ${NODE_MASTER}
    node.data: ${NODE_DATA}

    transport.tcp.port: ${TRANSPORT_PORT}
    http.port: ${HTTP_PORT}

    path.data: /data

    network.host: 0.0.0.0

    discovery.zen.minimum_master_nodes: ${MINIMUM_MASTER_NODES}

    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    discovery.zen.ping.unicast.hosts: ["elasticserach-logging-0", "elasticsearch-logging-1"]

    cluster.name: elasticsearch-pod
    node.name: ${HOSTNAME}
    network.host: 0.0.0.0
    
    bootstrap.memory_lock: false
    
    discovery.zen.minimum_master_nodes: 2
    discovery.zen.ping.unicast.hosts: ["es-0", "es-1", "es-2"]