kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azureloggingfilestorage
  namespace: kube-system
provisioner: kubernetes.io/azure-file
parameters:
  storageAccount: crdsintlogging
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azuretestfilestorage
  namespace: kube-system
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_RAGRS
  # storageAccount: crdsinttest3
